name: pypi
on:
  pull_request:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'
      - 'src/rez/utils/_version.py'
      - 'wiki/**'
      - 'metrics/**'
      - 'data/**'
      - '**.md'
  push:
    paths-ignore:
      - '.github/docker/**'
      - '.github/workflows/windows-docker-image.yaml'
      - 'src/rez/utils/_version.py'
      - 'wiki/**'
      - 'metrics/**'
      - 'data/**'
      - '**.md'

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          pip install flake8

      - name: Run flake8
        run: |
          ls *.py utils/*.py cli/*.py tests/*.py \
            xargs flake8
        working-directory: src/rez
