#
# This workflow just ensures the wiki builds correctly, it doesn't publish
# anything. See wiki-publish.yaml for publishing the wiki.
#

name: wiki-build
on:
  push:
    paths:
      - '.github/workflows/wiki-build.yaml'
      - 'wiki/**'
      - src/rez/rezconfig.py
env:
  CLONE_URL: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"

jobs:
  build:
    name: Build Wiki Artifact
    runs-on: ubuntu-latest
    env:
      TEMP_WIKI_DIR: "wiki/.rez-gen-wiki-tmp"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # required to generate credits list

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build Wiki
        working-directory: wiki
        run: |
          rezver=$(cat ./src/rez/utils/_version.py | grep -w _rez_version | tr '"' ' ' | awk '{print $NF}')

          python update-wiki.py \
            --keep-temp \
            --no-push \
            --github-release=${rezver} \
            --wiki-dir="${{ github.workspace }}"/"${{ env.TEMP_WIKI_DIR }}" \
            --wiki-url="${{ env.CLONE_URL }}"
