name: wintest

on:
  push:
    paths:
      - '.github/workflows/wintest.yaml'

jobs:
  base:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker repository
        run: |
          ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
          '${{ secrets.DOCKERHUB_TOKEN }}' | docker login -u ${gh_user} --password-stdin

      - name: Build base docker image if needed
        id: build_image
        run: |
          ${last_docker_base_rev} = $( `
            git log -n 1 --author-date-order --pretty=format:%H -- `
            .\.github\docker\rez-win-base\ `
            .\.github\workflows\windows-docker-image.yaml `
          ).SubString(0, 8)

          ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
          ${docker_image} = "${gh_user}/rez-win-base:${last_docker_base_rev}"

          Write-Output "Pulling DockerHub image ${docker_image}..."
          $ErrorActionPreference = "Continue"
          docker pull ${docker_image} 2>$null || Write-Output "(no such image)"
          #$ErrorActionPreference = "Stop"

          echo "hello"

          Write-Output "DUN IT"
